from app.generation.answer import (
    _build_answer_citations,
    _extract_citation_ids,
    _render_citations,
    _validate_citations,
    answer_question,
)
from app.generation.context import ContextSource
import pytest


def test_answerable_question_returns_grounded_answer():
    result = answer_question(
        "How does the LangChain Orchestrator process incoming requests?",
        limit=3,
    )

    assert result.text
    assert "Page 20" in result.text or "Page 21" in result.text

    assert result.citations

    citation_pages = {
        citation.page_number
        for citation in result.citations
    }

    assert 20 in citation_pages or 21 in citation_pages


def test_unanswerable_question_abstains_without_citations():
    result = answer_question(
        "What is the population of India according to this document?",
        limit=5,
    )

    assert (
        result.text
        == "The information about the population of India "
        "is not available in the provided documents."
    )

    assert result.citations == ()


def test_extract_citation_ids_supports_individual_citations():
    result = _extract_citation_ids(
        "Answer [1] and [4]."
    )

    assert result == [1, 4]


def test_extract_citation_ids_supports_grouped_citations():
    result = _extract_citation_ids(
        "Answer [1, 4, 5]."
    )

    assert result == [1, 4, 5]


def test_validate_citations_accepts_grouped_citations():
    result = _validate_citations(
        "Answer [1, 4].",
        {1, 4},
    )

    assert result == [1, 4]


def test_validate_citations_rejects_invalid_citation_id():
    with pytest.raises(
        ValueError,
        match=r"Invalid citation IDs generated by the model: \[10\]",
    ):
        _validate_citations(
            "Answer [10].",
            {1, 2, 3, 4, 5},
        )


def test_build_answer_citations_maps_ids_to_sources():
    sources = (
        ContextSource(
            citation_id=1,
            source="doc.pdf",
            page_number=20,
            chunk_index=10,
        ),
        ContextSource(
            citation_id=4,
            source="doc.pdf",
            page_number=169,
            chunk_index=345,
        ),
    )

    result = _build_answer_citations(
        [1, 4],
        sources,
    )

    assert [citation.page_number for citation in result] == [20, 169]


def test_render_citations_replaces_individual_citations():
    sources = (
        ContextSource(
            citation_id=1,
            source="doc.pdf",
            page_number=20,
            chunk_index=10,
        ),
        ContextSource(
            citation_id=4,
            source="doc.pdf",
            page_number=169,
            chunk_index=345,
        ),
    )

    citations = _build_answer_citations(
        [1, 4],
        sources,
    )

    result = _render_citations(
        "Answer [1] and [4].",
        citations,
    )

    assert result == "Answer [Page 20] and [Page 169]."


def test_render_citations_replaces_grouped_citations():
    sources = (
        ContextSource(
            citation_id=1,
            source="doc.pdf",
            page_number=20,
            chunk_index=10,
        ),
        ContextSource(
            citation_id=4,
            source="doc.pdf",
            page_number=169,
            chunk_index=345,
        ),
    )

    citations = _build_answer_citations(
        [1, 4],
        sources,
    )

    result = _render_citations(
        "Answer [1, 4].",
        citations,
    )

    assert result == "Answer [Page 20], [Page 169]."