import re
from dataclasses import dataclass

from app.generation.context import ContextSource, build_context
from app.llm.client import generate
from app.retrieval.search import SearchResult, search


@dataclass(frozen=True)
class AnswerCitation:
    citation_id: int
    source: str
    page_number: int
    chunk_index: int


@dataclass(frozen=True)
class Answer:
    text: str
    citations: tuple[AnswerCitation, ...]


SYSTEM_PROMPT = """
You are a grounded question-answering assistant.

Answer the user's question using ONLY the provided context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume facts that are not present in the context.
3. If the context does not contain enough information to answer the question,
   clearly say that the information is not available in the provided documents.
4. For an insufficient-information response, DO NOT include citations.
5. Keep the answer concise and directly answer the question.
6. Every factual claim in a normal answer must be supported by the provided context.
7. Cite supporting context using ONLY the citation IDs provided.
8. Citation IDs must use exactly this format: [1], [2], [3], etc.
9. NEVER invent a citation ID.
10. NEVER cite a page number or chunk number directly.
"""


def _extract_citation_ids(answer: str) -> list[int]:
    """
    Extract citation IDs such as [1], [2], [3].
    """

    return [
        int(value)
        for value in re.findall(r"\[(\d+)\]", answer)
    ]


def _validate_citations(
    answer: str,
    valid_ids: set[int],
) -> list[int]:
    """
    Validate that every citation refers to a retrieved source.
    """

    citation_ids = _extract_citation_ids(answer)

    invalid_ids = [
        citation_id
        for citation_id in citation_ids
        if citation_id not in valid_ids
    ]

    if invalid_ids:
        raise ValueError(
            f"Invalid citation IDs generated by the model: "
            f"{sorted(set(invalid_ids))}"
        )

    return citation_ids


def _build_answer_citations(
    citation_ids: list[int],
    sources: tuple[ContextSource, ...],
) -> tuple[AnswerCitation, ...]:
    """
    Convert model citation IDs into verified source metadata.
    """

    source_map = {
        source.citation_id: source
        for source in sources
    }

    citations = []

    for citation_id in dict.fromkeys(citation_ids):
        source = source_map[citation_id]

        citations.append(
            AnswerCitation(
                citation_id=source.citation_id,
                source=source.source,
                page_number=source.page_number,
                chunk_index=source.chunk_index,
            )
        )

    return tuple(citations)


def _render_citations(
    answer: str,
    citations: tuple[AnswerCitation, ...],
) -> str:
    """
    Replace internal citation IDs such as [1] with
    deterministic page citations such as [Page 20].
    """

    citation_map = {
        citation.citation_id: citation
        for citation in citations
    }

    def replace(match: re.Match[str]) -> str:
        citation_id = int(match.group(1))
        citation = citation_map.get(citation_id)

        if citation is None:
            return match.group(0)

        return f"[Page {citation.page_number}]"

    return re.sub(
        r"\[(\d+)\]",
        replace,
        answer,
    )


def abstain_answer() -> Answer:
    """Return the standard no-support response without citations."""

    return Answer(
        text=(
            "The provided documents do not contain enough "
            "information to answer this question."
        ),
        citations=(),
    )


def answer_from_results(
    question: str,
    results: list[SearchResult],
) -> Answer:
    """
    Generate a citation-aware answer from retrieved results.
    """

    built_context = build_context(results)

    if not built_context.text:
        return abstain_answer()

    prompt = f"""
Context:

{built_context.text}

Question:

{question}
"""

    generated_answer = generate(
        prompt=prompt,
        system_prompt=SYSTEM_PROMPT,
    )

    valid_ids = {
        source.citation_id
        for source in built_context.sources
    }

    citation_ids = _validate_citations(
        generated_answer,
        valid_ids,
    )

    citations = _build_answer_citations(
        citation_ids,
        built_context.sources,
    )

    rendered_answer = _render_citations(
        generated_answer,
        citations,
    )

    return Answer(
        text=rendered_answer,
        citations=citations,
    )


def answer_question(
    question: str,
    limit: int = 5,
) -> Answer:
    """
    Retrieve context and generate a citation-aware answer.
    """

    return answer_from_results(
        question,
        search(question, limit=limit),
    )

